# Generated by Django 4.2.5 on 2024-06-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_driver_is_superuser_driver_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='license_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='work_experience',
            field=models.IntegerField(default=3),
        ),
    ]
