# Generated by Django 4.2.5 on 2024-06-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_driver_first_name_driver_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='is_active',
        ),
    ]
