# Generated by Django 4.2.5 on 2024-06-28 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата брони')),
                ('time', models.TimeField(verbose_name='Время брони')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, verbose_name='Марка автомобиля')),
                ('model', models.CharField(max_length=255, verbose_name='Модель автомобиля')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('num_car', models.CharField(unique=True, verbose_name='Гос номер автомобиля')),
                ('car_status', models.CharField(choices=[('FREE', 'Free'), ('BUSY', 'Busy')], default='Free', max_length=100, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата поездки')),
                ('start_time', models.TimeField(verbose_name='Время начала поездки')),
                ('end_time', models.TimeField(verbose_name='Время окончания поездки')),
                ('destination', models.CharField(max_length=255, verbose_name='Место назначения')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('driver_status', models.CharField(choices=[('Awaiting order', 'Awaiting order'), ('Started', 'Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Awaiting order', max_length=100, verbose_name='Статус')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.car')),
            ],
            options={
                'verbose_name': 'Поездка',
                'verbose_name_plural': 'Поездки',
            },
        ),
    ]
