# Generated by Django 4.2.5 on 2024-06-28 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_as_driver', to='users.driver'),
        ),
        migrations.AddField(
            model_name='trip',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_as_passenger', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='rating',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.driver'),
        ),
        migrations.AddField(
            model_name='comment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.driver'),
        ),
        migrations.AddField(
            model_name='comment',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
        ),
        migrations.AddField(
            model_name='comment',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.driver'),
        ),
        migrations.AddField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_as_car', to='trips.car'),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_as_driver', to='users.driver'),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_as_passenger', to='users.customuser'),
        ),
    ]
