# Generated by Django 4.2.5 on 2024-07-01 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_driver_options_and_more'),
        ('trips', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not available', 'Not available')], default='Available', max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.driver', verbose_name='Водитель'),
        ),
    ]
