# Generated by Django 4.2.5 on 2024-06-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_booking_options_alter_car_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='num_car',
            field=models.CharField(unique=True, verbose_name='Гос номер автомобиля'),
        ),
    ]
